subjects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home',views.home, name= 'home'),
    path('signup',views.signup ,name='signup'),
    path('chemistry/chapters/level/medium/<int:id>', views.chemistry_medium),
    path('chemistry/chapters/level/easy/<int:id>', views.chemistry_easy),
    path('chemistry/chapters/level/hard/<int:id>', views.chemistry_hard),
    path('maths/chapters/level/medium/<int:id>', views.mathematics_medium),
    path('maths/chapters/level/easy/<int:id>', views.mathematics_easy),
    path('maths/chapters/level/hard/<int:id>', views.mathematics_hard),
    path('physics/chapters/level/medium/<int:id>', views.physics_medium),
    path('physics/chapters/level/hard/<int:id>', views.physics_hard),
    path('physics/chapters/level/easy/<int:id>', views.physics_easy),
    path('', views.login_in, name='login'),
    path('logout', views.log_out, name='logout'),
    path('chemistry/chapters', views.chemistry_chapters, name='chemistry_chapters'),
    path('chemistry/chapters/level/<int:id>', views.chemistry_level, name='chemistry_level'),
    path('maths/chapters', views.maths_chapters, name='maths_chapters'),
    path('maths/chapters/level/<int:id>', views.maths_level, name='maths_chapters'),
    path('physics/chapters', views.physics_chapters, name='physics_chapters'),
    path('physics/chapters/level/<int:id>', views.physics_level, name='physics_chapters'),
    path('chemistry_easy_result', views.chemistry_easy_result, name='chemistry_easy_result'),
    path('chemistry_medium_result', views.chemistry_medium_result, name='chemistry_medium_result'),
    path('chemistry_hard_result', views.chemistry_hard_result, name='chemistry_hard_result'),
    path('maths_easy_result', views.maths_easy_result, name='maths_easy_result'),
    path('maths_medium_result', views.maths_medium_result, name='maths_medium_result'),
    path('maths_hard_result', views.maths_hard_result, name='maths_hard_result'),
    path('physics_easy_result', views.physics_easy_result, name='physics_easy_result'),
    path('physics_medium_result', views.physics_medium_result, name='physics_medium_result'),
    path('physics_hard_result', views.physics_hard_result, name='physics_hard_result'),
    path('progress', views.progress, name='progress'),
]

subjects/models.py
from django.db import models
from django.contrib.auth.models import User


class Chemistry(models.Model):
    chapter = models.CharField(max_length=700)

    def __str__(self):
        return self.chapter


class ChemistryHard(models.Model):
    chemistry = models.ForeignKey(Chemistry, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class ChemistryHardOptions(models.Model):
    chemistry = models.ForeignKey(ChemistryHard, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class ChemistryEasy(models.Model):
    chemistry = models.ForeignKey(Chemistry, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class ChemistryEasyOptions(models.Model):
    chemistry = models.ForeignKey(ChemistryEasy, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class ChemistryMedium(models.Model):
    chemistry = models.ForeignKey(Chemistry, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class ChemistryMediumOptions(models.Model):
    chemistry = models.ForeignKey(ChemistryMedium, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class Physics(models.Model):
    chapter = models.CharField(max_length=700)

    def __str__(self):
        return self.chapter


class PhysicsHard(models.Model):
    chemistry = models.ForeignKey(Physics, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class PhysicsHardOptions(models.Model):
    chemistry = models.ForeignKey(PhysicsHard, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class PhysicsEasy(models.Model):
    chemistry = models.ForeignKey(Physics, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class PhysicsEasyOptions(models.Model):
    chemistry = models.ForeignKey(PhysicsEasy, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class PhysicsMedium(models.Model):
    chemistry = models.ForeignKey(Physics, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class PhysicsMediumOptions(models.Model):
    chemistry = models.ForeignKey(PhysicsMedium, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class Maths(models.Model):
    chapter = models.CharField(max_length=700)

    def __str__(self):
        return self.chapter


class MathsHard(models.Model):
    chemistry = models.ForeignKey(Maths, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class MathsHardOptions(models.Model):
    chemistry = models.ForeignKey(MathsHard, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class MathsEasy(models.Model):
    chemistry = models.ForeignKey(Maths, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class MathsEasyOptions(models.Model):
    chemistry = models.ForeignKey(MathsEasy, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class MathsMedium(models.Model):
    chemistry = models.ForeignKey(Maths, on_delete=models.CASCADE)
    question = models.CharField(max_length=2083)

    def __str__(self):
        return self.question


class MathsMediumOptions(models.Model):
    chemistry = models.ForeignKey(MathsMedium, on_delete=models.CASCADE)
    options = models.CharField(max_length=2083)
    answer = models.BooleanField()

    def __str__(self):
        return self.options


class ResultChemistry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    chemistry_hard = models.IntegerField(default=0)
    chemistry_easy = models.IntegerField(default=0)
    chemistry_medium = models.IntegerField(default=0)


class ResultMaths(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    maths_hard = models.IntegerField(default=0)
    maths_easy = models.IntegerField(default=0)
    maths_medium = models.IntegerField(default=0)


class ResultPhysics(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    physics_hard = models.IntegerField(default=0)
    physics_easy = models.IntegerField(default=0)
    physics_medium = models.IntegerField(default=0)


class Chat(models.Model):
    message = models.CharField(max_length=2083)



subjects/templates/subjects/physics/level/physics_easy.html
{% extends "subjects/base.html" %}
{% block title %} chemistry {% endblock %}

{% block subname %}<h2>Physics Easy Level Questions</h2> {% endblock %}

{% block content %}

  <form method="post" action="#">
           {% csrf_token %}
    {% for options in physics.all %}

      <p>{{options.id}}) {{options.question}}</p>

         {% for i in options.physicseasyoptions_set.all %}


           {% if i.answer == True %}
                 <input type="radio" id="2" name="fav_language{{options.id}}" value="Q" >
                 <label for="2">{{i}}</label><br>

             {% else %}
                <input type="radio" id="c" name="fav_language{{options.id}}" value="c">
             <label for="c">{{i}}</label><br>
           {% endif%}


         {% endfor %}
      {% endfor %}
      <input type="submit" name="submit">
    </form>

{% endblock %}

subjects/templates/subjects/physics/level/physics_hard.html
{% extends "subjects/base.html" %}
{% block title %} chemistry {% endblock %}

{% block subname %}<h2>physics hard Level Question</h2> {% endblock %}

{% block content %}

  <form method="post" action="#">
           {% csrf_token %}
    {% for options in physics.all %}

      <p>{{options.id}}) {{options.question}}</p>

         {% for i in options.physicshardoptions_set.all %}


           {% if i.answer == True %}
                 <input type="radio" id="2" name="fav_language{{options.id}}" value="Q" >
                 <label for="2">{{i}}</label><br>

             {% else %}
                <input type="radio" id="c" name="fav_language{{options.id}}" value="c">
             <label for="c">{{i}}</label><br>
           {% endif%}


         {% endfor %}
      {% endfor %}
      <input type="submit" name="submit">
    </form>

{% endblock %}

subjects/templates/subjects/physics/level/physics_medium.html
{% extends "subjects/base.html" %}
{% block title %} chemistry {% endblock %}

{% block subname %}<h2>physics medium Level Question</h2> {% endblock %}

{% block content %}

  <form method="post" action="#">
           {% csrf_token %}
    {% for options in physics.all %}

      <p>{{options.id}}) {{options.question}}</p>

         {% for i in options.physicsmediumoptions_set.all %}


           {% if i.answer == True %}
                 <input type="radio" id="2" name="fav_language{{options.id}}" value="Q" >
                 <label for="2">{{i}}</label><br>

             {% else %}
                <input type="radio" id="c" name="fav_language{{options.id}}" value="c">
             <label for="c">{{i}}</label><br>
           {% endif%}


         {% endfor %}
      {% endfor %}
      <input type="submit" name="submit">
    </form>

{% endblock %}

subjects/templates/subjects/physics/level/physicseasyresult.html
{{result}}

subjects/templates/subjects/physics/level/physicshardresult.html
{{result}}

subjects/templates/subjects/physics/level/physicsmediumresult.html
{{result}}